name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  ecs:
    uses: craftcms/.github/.github/workflows/ecs.yml@v1
  phpstan:
    uses: craftcms/.github/.github/workflows/phpstan.yml@v1
  notify_slack:
    needs: [ ecs, phpstan ]
    uses: craftcms/.github/.github/workflows/notify_slack.yml@v1
    with:
      success: ${{ needs.ecs.result == 'success' && needs.phpstan.result == 'success' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_PLUGIN_WEBHOOK_URL }}
      slack_group_id: ${{ secrets.SLACK_GROUP_ID }}
